/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MessageBubble: typeof import('./components/MessageBubble.vue')['default']
    MessageInput: typeof import('./components/MessageInput.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./components/SidebarItem.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
